project_name: Nengo Sphinx Theme
pkg_name: nengo_sphinx_theme
repo_name: nengo/nengo-sphinx-theme

description: Sphinx theme for Nengo project documentation pages
copyright_start: 2019
license: abr-free
main_branch: main

ci_scripts:
  - template: static
  - template: docs
  - template: deploy

contributing_rst: {}

contributors_rst: {}

license_rst: {}

manifest_in:
  global-include:
    - "*.conf"
    - "*.html"

setup_py:
  entry_points:
    sphinx.html_themes:
      - nengo_sphinx_theme=nengo_sphinx_theme
  include_package_data: True
  install_req:
    - sphinx>=7.2.6
    - sphinx-notfound-page>=1.0.0
  docs_req:
    - jupyter
    - matplotlib
    - nbsphinx
    - nengo
    - numpydoc
  classifiers:
    - "Development Status :: 4 - Beta"
    - "Framework :: Nengo"
    - "Intended Audience :: Developers"
    - "Operating System :: Microsoft :: Windows"
    - "Operating System :: POSIX :: Linux"
    - "Programming Language :: Python"
    - "Programming Language :: Python :: 3.9"
    - "Topic :: Software Development"

setup_cfg:
  pylint:
    disable:
      - consider-using-f-string # TODO: remove this once we have tests
      - missing-docstring

docs_conf_py:
  exclude_patterns:
    - examples/test-example.ipynb
  extensions:
    - nengo_sphinx_theme.ext.resolvedefaults
    - nengo_sphinx_theme.ext.autoautosummary
  html_redirects:
    redirect/to/nested-page.html: deeply/nested/testing/page.html
    redirect/to/external.html: https://www.nengo.ai/
  autoautosummary_change_modules:
    nengo_sphinx_theme.ext.renamed_autoautosummary:
      - nengo_sphinx_theme.ext.autoautosummary.TestClass
      - nengo_sphinx_theme.ext.autoautosummary.a_test_function
  sphinx_options:
    autodoc_typehints: "'none'"
    linkcheck_ignore: linkcheck_ignore + [r"redirect/to/.*.html"]

pre_commit_config_yaml: {}

pyproject_toml: {}

version_py:
  type: calver
  release: false
